services:
  user-service:
    build: ./user-service
    ports:
      - "3001:3001"

  product-service:
    build: ./product-service
    ports:
      - "3002:3002"

  order-service:
    build: ./order-service
    ports:
      - "3003:3003"

  payment-service:
    build: ./payment-service
    ports:
      - "3004:3004"
